language: php

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4snapshot

sudo: false

cache:
  directories:
    - $HOME/.composer/cache/files

env:
  matrix:
    - SYMFONY_VERSION='4.0.*'
    - SYMFONY_VERSION='4.1.*'
    - SYMFONY_VERSION='4.2.*'
    - SYMFONY_VERSION='4.3.*'

jobs:
  allow_failures:
    - php: 7.4snapshot

before_install:
  - phpenv config-rm xdebug.ini || true
  - composer self-update
  - composer require symfony/framework-bundle:${SYMFONY_VERSION} --no-update

install: composer update --prefer-dist

script:
  - SYMFONY_DEPRECATIONS_HELPER=weak vendor/bin/simple-phpunit ${PHPUNIT_FLAGS}

notifications:
  email:
    - willemsen.christophe@gmail.com
    - mb@lunetics.com
